matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      sudo: required
script:
  - cd Stack && swift test && cd ..
  - cd Queue && swift test && cd ..
  - cd InsertionSort && swift test && cd ..
  - cd BubbleSort && swift test && cd ..
  - cd MergeSort && swift test && cd ..
  - cd QuickSort && swift test && cd ..
  - cd SelectionSort && swift test && cd ..
  - cd JumpSearch && swift test && cd ..
  - cd LinearSearch && swift test && cd ..
  - cd LinkedList && swift test && cd ..
  - cd BinarySearch && swift test && cd ..
  - cd HashTable && swift test && cd ..
before_install:
  - chmod ugo+x ./.scripts/InstallSwift.sh
  - . ./.scripts/InstallSwift.sh
notifications:
  email:
    on_success: never
    on_failure: change
