matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
    - os: osx
      language: objective-c
      osx_image: xcode7.3
script:
  - swift build
  - swift test
notifications:
  email: false
