matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      sudo: required
script:
	make test
before_install:
  - chmod ugo+x ./.scripts/InstallSwift.sh
  - . ./.scripts/InstallSwift.sh
  - chmod ugo+x ./.scripts/InstallCUnit.sh
  - . ./.scripts/InstallCUnit.sh
notifications:
  email:
    on_success: never
    on_failure: change
